<script type="text/javascript">const habitIds = <?=json_encode(array_map(function($h) { return $h->getId(); }, $this->data))?></script>
<h1>
    <span class="toggle-allhabits closed" id="toggle-habit-all-opener"><i class="fa fa-plus-square-o" aria-hidden="true"></i> </span>
    <span class="toggle-allhabits open" id="toggle-habit-all-closer"><i class="fa fa-minus-square-o" aria-hidden="true"></i> </span>
    All Habits
</h1>
<?php foreach ($this->data as $habit): ?>
    <h2>
        <span class="toggle-habit closed" id="toggle-habit-<?=$habit->getId()?>-opener" data-habitid="<?=$habit->getId()?>"><i class="fa fa-plus-square-o" aria-hidden="true"></i> </span>
        <span class="toggle-habit open" id="toggle-habit-<?=$habit->getId()?>-closer" data-habitid="<?=$habit->getId()?>"><i class="fa fa-minus-square-o" aria-hidden="true"></i> </span>
        <?=$habit->getName()?>
    </h2>
    <h2>
        <span class="previous-habit" data-habitid="<?=$habit->getId()?>">
            <i class="fa fa-arrow-circle-o-up" aria-hidden="true"></i>
        </span>
    </h2>
    <div class="habit openable" id="content-habit-<?=$habit->getId()?>">
        <?php 
            $now = new \DateTime();
            $currentYearAndMonth = [ 'year' => $now->format('Y'), 'month' => $now->format('m') ];
        ?>
        <?php foreach ($habit->getMonthHeadings($currentYearAndMonth) as $monthHeading):?>
            <h3 data-month-combi="<?=$habit->getId().'-'.$monthHeading['year'] .'-'. $monthHeading['month']?>" class="month-heading"><?=$monthHeading['year'] .'/'. $monthHeading['month']?></h3>
            <table data-month-combi="<?=$habit->getId().'-'.$monthHeading['year'] .'-'. $monthHeading['month']?>" class="month-table<?=\Util::isCurrentMonthHeading($monthHeading) ? ' current' : ''?>">
                <tr>
                    <th>&nbsp;</th>
                    <th>Mo</th>
                    <th>Di</th>
                    <th>Mi</th>
                    <th>Do</th>
                    <th>Fr</th>
                    <th>Sa</th>
                    <th>So</th>
                <?php $rdfm = $habit->getResolutionsDatesForMonth($monthHeading['year'], $monthHeading['month']);
                if (count($rdfm) > 0):?>
                    <?=$this->includeTemplate('habit_calendar_range', ['resolutionDates' => $rdfm, 'habit' => $habit]);?>
                <?php endif;?>
            </table>
        <?php endforeach;?>
    </div>
    <h2>
        <span class="next-habit" data-habitid="<?=$habit->getId()?>">
            <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i>
        </span>
    </h2>
    <hr/>
<?php endforeach; ?>
