<div id="habit-container" class="main-container list-container">
    <form method="post">
        <input type="hidden" name="action" value="<?=$this->data['action']?>"/>
        <table class="config">
            <?php $habit = $this->data['habit'];?>
            <?php if ($habit->getId()):?>
                <tr>
                    <th>ID:</th><td><input type="hidden" name="id" value="<?= static::h($habit->getId())?>"/><?= static::h($habit->getId())?></td>
                </tr>
            <?php endif;?>
            <tr>
                <th>Name:</th><td><input type="text" name="name" size="30" maxlength="255" value="<?= static::h($habit->getName())?>"/></td>
            </tr>
            <tr>
                <th>Description:</th><td><input type="text" name="description" size="30" maxlength="255" value="<?= static::h($habit->getDescription())?>"/></td>
            </tr>
            <tr>
                <th>Start Date (Y-m-d):</th><td><input type="text" class="date" name="start_date" size="10" maxlength="10" value="<?= static::h($habit->getStartDateFormatted())?>"/></td>
            </tr>
            <tr>
                <th>End Date (Y-m-d):</th><td><input type="text" class="date" name="end_date" size="10" maxlength="10" value="<?= static::h($habit->getEndDateFormatted())?>"/></td>
            </tr>
            <tr>
                <th>Is Fulfilment Relative?:</th>
                <td><input type="checkbox" name="is_fulfilment_relative" value="1" <?php if ($habit->getIsFulfilmentRelative()):?> checked="checked"<?php endif?>/></td>
            </tr>
            <tr>
                <th>Fulfilment Unit:</th><td><input type="text" name="fulfilment_unit" size="10" maxlength="10" value="<?= static::h($habit->getFulfilmentUnit())?>"/></td>
            </tr>
            <tr>
                <th>Fulfilment Max:</th><td><input type="text" name="fulfilment_max" size="10" maxlength="10" value="<?= static::h($habit->getFulfilmentMax())?>"/></td>
            </tr>
            <tr>
                <th>Week days:</th>
                <td>
                    <table>
                        <tr>
                            <?php $weekDays = $habit->getWeekDays();
                            $weekDayNames = \Util::weekDayNames;
                            for ( $num = 0; $num < 7; ++$num ):?>
                                <th><?=$weekDayNames[$num]?></th>
                            <?php endfor; ?>
                        </tr>
                        <tr>
                            <?php $weekDays = $habit->getWeekDays();
                            $weekDayNames = \Util::weekDayNames;
                            for ( $num = 0; $num < 7; ++$num ):?>
                                    <td><input type="checkbox" name="weekday_<?=$num?>" value="1"<?php if ( $habit->hasWeekDay($num) ):?> checked="checked"<?php endif;?> /></td>
                            <?php endfor; ?>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <th></th><td><input type="submit" name="save" value="Save" /></td>
            </tr>
        <table>
        <?php if ($habit->getId()):?> 
            <a href="resolutions.php?action=list&habit_id=<?=$habit->getId()?>">Resolutions</a> <br/>
            <a href="pauses.php?action=list&habit_id=<?=$habit->getId()?>">Pauses</a>
        <?php endif;?>
    </form>
</div>
