<div id="login-container" class="main-container list-container">
    <form method="post">
        <input type="hidden" name="action" value="login"/>
        <table class="login">
            <tr>
                <th>Login:</th><td><input type="text" name="login" size="30" maxlength="255" value=""/></td>
            </tr>
            <tr>
                <th>Password:</th><td><input type="password" name="password" size="30" maxlength="255" value=""/></td>
            </tr>
            <tr>
                <th></th><td><input type="submit" name="save" value="Login" /></td>
            </tr>
        <table>
    </form>
</div>
