<div id="user-container" class="main-container list-container">
    <form method="post">
        <input type="hidden" name="action" value="<?=$this->data['action']?>"/>
        <table class="config">
            <?php $user = $this->data['user'];?>
            <?php if ($user->getId()):?>
                <tr>
                    <th>ID:</th><td><input type="hidden" name="id" value="<?= static::h($user->getId())?>"/><?= static::h($user->getId())?></td>
                </tr>
            <?php endif;?>
            <tr>
                <th>Name:</th><td><input type="text" name="name" size="30" maxlength="255" value="<?= static::h($user->getName())?>"/></td>
            </tr>
            <tr>
                <th>Login:</th><td><input type="text" name="login" size="30" maxlength="255" value="<?= static::h($user->getLogin())?>"/></td>
            </tr>
            <tr>
                <th>Password:</th><td><input type="password" name="password" size="30" maxlength="255" value=""/></td>
            </tr>
            <tr>
                <th>Password:</th><td><input type="password" name="password2" size="30" maxlength="255" value=""/></td>
            </tr>
            <tr>
                <th></th><td><input type="submit" name="save" value="Save" /></td>
            </tr>
        <table>
        <?php if ($user->getId()):?> <a href="habits.php?action=list&user_id=<?=$user->getId()?>">Habits</a></td> <?php endif;?>
    </form>
</div>
